-- 코드를 입력하세요
WITH TMP AS(
SELECT *, DATEDIFF(END_DATE, START_DATE)+1 AS 'DIFF', IF(DATEDIFF(END_DATE, START_DATE)+1 >= 90, '90일 이상', IF(DATEDIFF(END_DATE, START_DATE)+1 >= 30, '30일 이상', IF(DATEDIFF(END_DATE, START_DATE)+1 >= 7, '7일 이상', NULL))) AS 'DURATION_TYPE' 
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H USING(CAR_ID)
WHERE CAR_TYPE = '트럭')

SELECT HISTORY_ID, IF(ISNULL(PLAN_ID), ROUND(DIFF*DAILY_FEE, 0), ROUND(((DIFF*DAILY_FEE)*(100-DISCOUNT_RATE)*0.01), 0)) AS 'FEE'
FROM TMP
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN USING(DURATION_TYPE, CAR_TYPE)
ORDER BY FEE DESC, HISTORY_ID DESC