-- 코드를 작성해주세요
SELECT SUM(SCORE) AS 'SCORE', EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_DEPARTMENT D
     JOIN HR_EMPLOYEES E USING(DEPT_ID)
     JOIN HR_GRADE G USING(EMP_NO)
WHERE YEAR = '2022'
GROUP BY EMP_NO
ORDER BY SCORE DESC LIMIT 1